Add tests for debrepo split_pkg_path
knazarov/mkrepo pull request #35
Opened 2021-08-01 20:56 UTC by knazarov

This pull request adds basic tests for split_pkg_path to be used in validation of #29

2021-08-13 13:49 UTC, LeonidVas requested changes
Hi! Thank you for the patch.
Generally ok but I have several comments.
I also want to suggest that you use https://github.com/tarantool/tarantool/wiki/Code-review-procedure#commit-message for style of commits, because in this case it is easy enough to understand from the commit title/message what was done, where and why.

2021-08-13 13:49 UTC, LeonidVas commented on test/test_debrepo.py
> +            #(
Each line of a block comment starts with a # and a single space '# ' (https://www.python.org/dev/peps/pep-0008/#block-comments)

2021-08-13 13:49 UTC, LeonidVas commented on test/test_debrepo.py
> +            #),
Each line of a block comment starts with a # and a single space '# ' (https://www.python.org/dev/peps/pep-0008/#block-comments)

2021-08-13 13:49 UTC, LeonidVas commented on test/test_debrepo.py
> +            #(
Each line of a block comment starts with a # and a single space '# ' (https://www.python.org/dev/peps/pep-0008/#block-comments)

2021-08-13 13:49 UTC, LeonidVas commented on test/test_debrepo.py
> +            #),
Each line of a block comment starts with a # and a single space '# ' (https://www.python.org/dev/peps/pep-0008/#block-comments)

2021-08-13 13:49 UTC, LeonidVas commented on test/test_debrepo.py
> +                version[0])
I think this message should be more verbose (programmer friendly).

2021-08-23 19:51 UTC, knazarov commented on test/test_debrepo.py
> +                version[0])
I've removed the message completely, because what unittest shows by default is good enough.

2021-08-23 19:53 UTC, knazarov commented
@LeonidVas I've updated the code according to comments

2021-08-31 13:36 UTC, LeonidVas approved these changes
LGTM.

2021-09-04 14:04 UTC, merged

2021-09-04 14:24 UTC, Totktonada commented
Nice, thank you guys!