Fix parsing Ubuntu Impish (and higher) deb pkgs
knazarov/mkrepo pull request #60
Opened 2022-05-23 10:02 UTC by ylobankov

It looks like control TAR archive for Ubuntu Impish (and higher) has
the `zst` suffix now instead of `xz`. This patch fixes the issue.

Fixes #59

2022-05-23 10:15 UTC, Totktonada approved these changes
Visually it looks ok. Did you test it manually? Please, share results.

2022-05-23 11:05 UTC, Totktonada commented
@knazarov said in a private conversation that he does not mind the change.

2022-05-23 11:10 UTC, ylobankov commented
> Visually it looks ok. Did you test it manually? Please, share results.

Yep, it was tested on the openssl package from Ubuntu Impish repo.

2022-05-23 11:13 UTC, LeonidVas reviewed
Hi! Thank you for the patch.
Several nits:
* Commit title - I suggest to write it according to https://github.com/tarantool/tarantool/wiki/Code-review-procedure#commit-message (`deb: fix...`). It is just convenient to have the same commit format in all the repositories.
* You can add a link to https://balintreczey.hu/blog/hello-zstd-compressed-debs-in-ubuntu/  Up to you.
* Add tests for the `parse_deb` method.

2022-05-23 20:04 UTC, Totktonada commented on test/test_debrepo.py
> +                self.fail('parse_deb() raised FileNotFoundError unexpectedly!')
How about checking return values?

2022-05-23 21:27 UTC, ylobankov commented on test/test_debrepo.py
> +                self.fail('parse_deb() raised FileNotFoundError unexpectedly!')
Checking return values is not in the scope of this PR. I just added one more variant of extracting the `control.tar` archive. I didn't touch `self.parse_string()` method.

2022-05-24 07:49 UTC, LeonidVas requested changes

2022-05-24 07:49 UTC, LeonidVas commented on test/test_debrepo.py
> +    def test_control_tar_archive(self):
It looks like this test has nothing to do with the class `TestVersionParsing` I think a new class should be created `TestIndexUnit` and within that class `test_control_tar_archive` would be relevant.

2022-05-24 07:49 UTC, LeonidVas commented on test/test_debrepo.py
> +                self.fail('parse_deb() raised FileNotFoundError unexpectedly!')
In fact, it looks like a bit of work from above, thanks to which you can find out that the method not only does not throw exceptions, but also works.

2022-05-24 10:34 UTC, ylobankov commented on test/test_debrepo.py
> +    def test_control_tar_archive(self):
You are absolutely right. Thanks, fixed.

2022-05-24 10:40 UTC, ylobankov commented on test/test_debrepo.py
> +                self.fail('parse_deb() raised FileNotFoundError unexpectedly!')
Ok guys, fixed.

2022-05-24 10:53 UTC, LeonidVas approved these changes
LGTM

2022-05-24 10:56 UTC, merged